=== getsentry/sentry-kafka-schemas/schemas/group-attributes.v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/GroupAttributesSnapshot",
  "definitions": {
    "GroupAttributesSnapshot": {
      "type": "object",
      "title": "group_attributes_snapshot",
      "properties": {
        "group_deleted": {
          "type": "boolean"
        },
        "project_id": {
          "type": "integer"
        },
        "group_id": {
          "type": "integer"
        },
        "status": {
          "type": "integer"
        },
        "substatus": {
          "type": ["integer", "null"]
        },
        "first_seen": {
          "type": "string"
        },
        "num_comments": {
          "type": "integer"
        },
        "assignee_user_id": {
          "type": ["integer", "null"]
        },
        "assignee_team_id": {
          "type": ["integer", "null"]
        },
        "owner_suspect_commit_user_id": {
          "type": ["integer", "null"]
        },
        "owner_ownership_rule_user_id": {
          "type": ["integer", "null"]
        },
        "owner_ownership_rule_team_id": {
          "type": ["integer", "null"]
        },
        "owner_codeowners_user_id": {
          "type": ["integer", "null"]
        },
        "owner_codeowners_team_id": {
          "type": ["integer", "null"]
        },
        "timestamp": {
          "type": "string"
        }
      },
      "required": [
        "group_deleted",
        "project_id",
        "group_id",
        "status",
        "substatus",
        "first_seen",
        "num_comments",
        "assignee_user_id",
        "assignee_team_id",
        "owner_suspect_commit_user_id",
        "owner_ownership_rule_user_id",
        "owner_ownership_rule_team_id",
        "owner_codeowners_user_id",
        "owner_codeowners_team_id",
        "timestamp"
      ]
    }
  }
}

=== getsentry/sentry-kafka-schemas/examples/group-attributes/1/owner_changed.json
{
  "group_deleted": false,
  "project_id": 1,
  "group_id": 1,
  "status": 0,
  "substatus": 7,
  "first_seen": "2023-02-27T15:40:12.223000Z",
  "num_comments": 0,
  "assignee_user_id": 123,
  "assignee_team_id": null,
  "owner_suspect_commit_user_id": null,
  "owner_ownership_rule_user_id": null,
  "owner_ownership_rule_team_id": 456,
  "owner_codeowners_user_id": null,
  "owner_codeowners_team_id": null,
  "timestamp": "2023-02-27T15:41:22.000000Z"
}

=== getsentry/sentry-kafka-schemas/examples/group-attributes/1/group_deleted.json
{
  "group_deleted": true,
  "project_id": 1,
  "group_id": 1,
  "status": 4,
  "substatus": null,
  "first_seen": "2023-02-27T15:40:12.223000Z",
  "num_comments": 0,
  "assignee_user_id": null,
  "assignee_team_id": null,
  "owner_suspect_commit_user_id": null,
  "owner_ownership_rule_user_id": null,
  "owner_ownership_rule_team_id": null,
  "owner_codeowners_user_id": null,
  "owner_codeowners_team_id": null,
  "timestamp": "2023-02-27T15:42:12.000000Z"
}
