=== getsentry/sentry-kafka-schemas/schemas/ingest-metrics.v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/IngestMetric",
  "definitions": {
    "IngestMetric": {
      "type": "object",
      "title": "ingest_metric",
      "additionalProperties": false,
      "properties": {
        "org_id": {
          "description": "The organization for which this metric is being sent.",
          "type": "integer"
        },
        "project_id": {
          "description": "The project for which this metric is being sent.",
          "type": "integer"
        },
        "name": {
          "description": "The metric name. Relay sometimes calls this an MRI and makes assumptions about its string shape, and those assumptions also exist in certain queries. The rest of the ingestion pipeline treats it as an opaque string.",
          "type": "string"
        },
        "type": {
          "description": "The metric type. [c]ounter, [d]istribution, [s]et. Relay additionally defines Gauge, but that metric type is completely unsupported downstream.",
          "type": "string",
          "enum": ["c", "d", "s"]
        },
        "timestamp": {
          "description": "The timestamp at which this metric was being sent. Relay will round this down to the next 10-second interval.",
          "type": "integer"
        },
        "tags": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "value": {
          "anyOf": [
            {
              "title": "number_metric_value",
              "type": "number"
            },
            {
              "title": "numbers_metric_value",
              "type": "array",
              "items": {
                "type": "number"
              }
            }
          ]
        },
        "retention_days": {
          "type": "integer"
        }
      },
      "required": [
        "name",
        "org_id",
        "project_id",
        "retention_days",
        "tags",
        "timestamp",
        "type",
        "value"
      ]
    }
  }
}

=== getsentry/sentry-kafka-schemas/examples/ingest-metrics/1/basic-counter.json
{
  "org_id": 420,
  "project_id": 420,
  "name": "c:sessions/session@none",
  "tags": {
    "sdk": "raven-node/2.6.3",
    "environment": "production",
    "release": "sentry-test@1.0.0",
    "session.status": "init"
  },
  "timestamp": 1111111111111111,
  "retention_days": 90,
  "type": "c",
  "value": 1
}
