=== getsentry/sentry-kafka-schemas/schemas/ingest-spans.v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "spans_stream_message",
  "$ref": "#/definitions/SpanEvent",
  "definitions": {
    "SpanEvent": {
      "type": "object",
      "title": "span_event",
      "additionalProperties": true,
      "properties": {
        "event_id": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UUID"
        },
        "organization_id": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UInt"
        },
        "project_id": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UInt"
        },
        "key_id": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UInt"
        },
        "trace_id": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UUID",
          "description": "The trace ID is a unique identifier for a trace. It is a 16 byte hexadecimal string."
        },
        "span_id": {
          "type": "string",
          "description": "The span ID is a unique identifier for a span within a trace. It is an 8 byte hexadecimal string."
        },
        "parent_span_id": {
          "type": ["string", "null"],
          "description": "The parent span ID is the ID of the span that caused this span. It is an 8 byte hexadecimal string."
        },
        "start_timestamp": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/PositiveFloat",
          "description": "UNIX timestamp in seconds with fractional part up to microsecond precision."
        },
        "end_timestamp": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/PositiveFloat",
          "description": "UNIX timestamp in seconds with fractional part up to microsecond precision."
        },
        "retention_days": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UInt16"
        },
        "downsampled_retention_days": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UInt16"
        },
        "received": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/PositiveFloat",
          "description": "Unix timestamp when the span was received by Sentry."
        },
        "name": {
          "type": ["string", "null"]
        },
        "status": {
          "type": "string"
        },
        "is_segment": {
          "type": ["boolean", "null"]
        },
        "accepted_outcome_emitted": {
          "type": ["boolean", "null"]
        },
        "links": {
          "type": ["array", "null"],
          "items": {
            "oneOf": [
              {
                "$ref": "file://ingest-spans.v1.schema.json#/definitions/SpanLink"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "attributes": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/Attributes"
        },
        "_meta": {
          "type": "object"
        }
      },
      "required": [
        "organization_id",
        "project_id",
        "received",
        "retention_days",
        "span_id",
        "start_timestamp",
        "end_timestamp",
        "trace_id",
        "name",
        "status"
      ]
    },
    "UUID": {
      "type": "string",
      "minLength": 32,
      "maxLength": 36
    },
    "UInt16": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    },
    "UInt32": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4294967295
    },
    "UInt": {
      "type": "integer",
      "minimum": 0
    },
    "PositiveFloat": {
      "type": "number",
      "minimum": 0
    },
    "SpanLink": {
      "type": ["object"],
      "title": "span_link",
      "additionalProperties": true,
      "properties": {
        "trace_id": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/UUID"
        },
        "span_id": {
          "type": "string"
        },
        "attributes": {
          "$ref": "file://ingest-spans.v1.schema.json#/definitions/Attributes"
        },
        "sampled": {
          "type": ["boolean", "null"]
        }
      },
      "required": ["trace_id", "span_id"]
    },
    "Attributes": {
      "type": ["object", "null"],
      "additionalProperties": {
        "oneOf": [
          {
            "$ref": "file://ingest-spans.v1.schema.json#/definitions/AttributeValue"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "AttributeValue": {
      "type": "object",
      "properties": {
        "type": {
          "enum": ["boolean", "integer", "double", "string", "array", "object"]
        },
        "value": {
          "type": ["number", "null", "string", "boolean", "array", "object"]
        }
      },
      "required": ["type", "value"]
    }
  }
}

=== getsentry/sentry-kafka-schemas/examples/ingest-spans/1/span_with_accepted_outcome.json
{
  "organization_id": 1,
  "project_id": 42,
  "key_id": 123,
  "event_id": "cbf6960622e14a45abc1f03b2055b186",
  "received": 1759215783.850951,
  "retention_days": 90,
  "downsampled_retention_days": 90,
  "accepted_outcome_emitted": false,
  "attributes": {
    "sentry.category": {
      "type": "string",
      "value": "http"
    },
    "sentry.description": {
      "type": "string",
      "value": "GET /api/0/organizations/?member=1"
    },
    "sentry.group": {
      "type": "string",
      "value": "37e3d9fab1ae9162"
    },
    "sentry.is_segment": {
      "type": "boolean",
      "value": false
    },
    "sentry.name": {
      "type": "string",
      "value": "http"
    },
    "sentry.normalized_description": {
      "type": "string",
      "value": "GET *"
    },
    "sentry.op": {
      "type": "string",
      "value": "http"
    },
    "sentry.origin": {
      "type": "string",
      "value": "manual"
    },
    "sentry.platform": {
      "type": "string",
      "value": "other"
    },
    "sentry.sdk.name": {
      "type": "string",
      "value": "raven-node"
    },
    "sentry.sdk.version": {
      "type": "string",
      "value": "2.6.3"
    },
    "sentry.segment.id": {
      "type": "string",
      "value": "968cff94913ebb07"
    },
    "sentry.status": {
      "type": "string",
      "value": "ok"
    },
    "sentry.trace.status": {
      "type": "string",
      "value": "ok"
    },
    "sentry.transaction": {
      "type": "string",
      "value": "hi"
    },
    "sentry.transaction.op": {
      "type": "string",
      "value": "hi"
    },
    "foo": null
  },
  "end_timestamp": 1759215782.849409,
  "is_segment": false,
  "links": [
    {
      "trace_id": "0f62a8b040f340bda5d830223def1d82",
      "span_id": "cbbbbbbbbbbbbbbc",
      "sampled": true,
      "attributes": {
        "span_key": {
          "type": "string",
          "value": "span_value"
        }
      }
    },
    {
      "trace_id": "0f62a8b040f340bda5d830223def1d82",
      "span_id": "cbbbbbbbbbbbbbbd",
      "sampled": null,
      "attributes": {
        "span_key": null
      }
    },
    {
      "trace_id": "0f62a8b040f340bda5d830223def1d82",
      "span_id": "cbbbbbbbbbbbbbbe",
      "attributes": null
    }
  ],
  "name": "http",
  "parent_span_id": "968cff94913ebb07",
  "span_id": "bbbbbbbbbbbbbbbb",
  "start_timestamp": 1759215782.349409,
  "status": "ok",
  "trace_id": "ff62a8b040f340bda5d830223def1d81"
}

=== getsentry/sentry-kafka-schemas/examples/ingest-spans/1/missing_fields.json
{
  "organization_id": 1,
  "project_id": 42,
  "key_id": 123,
  "event_id": "cbf6960622e14a45abc1f03b2055b186",
  "received": 1759215783.850951,
  "retention_days": 90,
  "downsampled_retention_days": 90,
  "end_timestamp": 1759215782.849409,
  "name": null,
  "span_id": "bbbbbbbbbbbbbbbb",
  "start_timestamp": 1759215782.349409,
  "status": "ok",
  "trace_id": "ff62a8b040f340bda5d830223def1d81"
}

=== getsentry/sentry-kafka-schemas/examples/ingest-spans/1/null_fields.json
{
  "organization_id": 1,
  "project_id": 42,
  "key_id": 123,
  "event_id": "cbf6960622e14a45abc1f03b2055b186",
  "received": 1759215783.850951,
  "retention_days": 90,
  "downsampled_retention_days": 90,
  "attributes": null,
  "end_timestamp": 1759215782.849409,
  "is_segment": null,
  "accepted_outcome_emitted": null,
  "links": null,
  "name": null,
  "parent_span_id": null,
  "span_id": "bbbbbbbbbbbbbbbb",
  "start_timestamp": 1759215782.349409,
  "status": "ok",
  "trace_id": "ff62a8b040f340bda5d830223def1d81"
}
