=== getsentry/sentry-kafka-schemas/schemas/profile-metadata.v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProfileMetadata",
  "title": "profile_metadata",
  "definitions": {
    "ProfileMetadata": {
      "type": "object",
      "properties": {
        "android_api_level": {
          "type": "integer"
        },
        "architecture": {
          "type": "string"
        },
        "device_classification": {
          "type": "string"
        },
        "device_locale": {
          "type": "string"
        },
        "device_manufacturer": {
          "type": "string"
        },
        "device_model": {
          "type": "string"
        },
        "device_os_build_number": {
          "type": "string"
        },
        "device_os_name": {
          "type": "string"
        },
        "device_os_version": {
          "type": "string"
        },
        "duration_ns": {
          "$ref": "#/definitions/UInt"
        },
        "environment": {
          "type": "string"
        },
        "profile_id": {
          "type": "string"
        },
        "organization_id": {
          "$ref": "#/definitions/UInt"
        },
        "platform": {
          "type": "string"
        },
        "project_id": {
          "$ref": "#/definitions/UInt"
        },
        "received": {
          "type": "integer"
        },
        "retention_days": {
          "type": "integer"
        },
        "trace_id": {
          "type": "string"
        },
        "transaction_id": {
          "type": "string"
        },
        "transaction_name": {
          "type": "string"
        },
        "version_code": {
          "type": "string"
        },
        "version_name": {
          "type": "string"
        }
      },
      "required": [
        "device_locale",
        "device_manufacturer",
        "device_model",
        "device_os_name",
        "device_os_version",
        "duration_ns",
        "profile_id",
        "organization_id",
        "platform",
        "project_id",
        "received",
        "retention_days",
        "trace_id",
        "transaction_id",
        "transaction_name",
        "version_code",
        "version_name"
      ]
    },
    "UInt": {
      "type": "integer",
      "minimum": 0
    }
  }
}

=== getsentry/sentry-kafka-schemas/examples/profile-metadata/1/basic.json
{
  "architecture": "x86_64",
  "device_locale": "",
  "device_manufacturer": "",
  "device_model": "",
  "device_os_name": "Linux",
  "device_os_version": "4.14.281-212.502.amzn2.x86_64",
  "duration_ns": 55659715,
  "environment": "staging-staging",
  "profile_id": "f851b3c2d70d4f119b3a49ce9f630194",
  "organization_id": 1,
  "platform": "python",
  "project_id": 1,
  "received": 1687971966,
  "retention_days": 90,
  "trace_id": "cbf7414c931448e98ed3f9b4e239a58e",
  "transaction_id": "6d15f5585cbd4b92945c605314f760cd",
  "transaction_name": "GET /events",
  "version_code": "",
  "version_name": ""
}
