=== getsentry/sentry-kafka-schemas/schemas/snuba-items.v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "item",
  "type": "object",
  "properties": {
    "organization_id": {
      "$ref": "#/definitions/UInt"
    },
    "project_id": {
      "$ref": "#/definitions/UInt"
    },
    "trace_id": {
      "$ref": "#/definitions/UUID"
    },
    "item_id": {
      "$ref": "#/definitions/UInt"
    },
    "item_type": {
      "type": "integer",
      "enum": [1, 2, 3]
    },
    "attributes": {
      "$ref": "#/definitions/Attributes"
    },
    "received": {
      "$ref": "#/definitions/Timestamp"
    },
    "retention_days": {
      "$ref": "#/definitions/UInt"
    }
  },
  "required": [
    "organization_id",
    "project_id",
    "trace_id",
    "item_id",
    "item_type",
    "attributes",
    "received",
    "retention_days"
  ],
  "definitions": {
    "Attributes": {
      "type": "object"
    },
    "UUID": {
      "type": "string",
      "minLength": 32,
      "maxLength": 36
    },
    "UInt": {
      "type": "integer",
      "minimum": 0
    },
    "Timestamp": {
      "type": "number",
      "minimum": 0
    }
  }
}

=== getsentry/sentry-kafka-schemas/examples/snuba-items/1/valid.json
{
  "organization_id": 1,
  "project_id": 1,
  "trace_id": "bf08190abab048fdb5cc5bf815787f59",
  "item_id": 1234567890123456,
  "item_type": 1,
  "attributes": {
    "sentry.environment": "production",
    "sentry.is_segment": true,
    "sentry.start_timestamp": 1741792974.123456,
    "http.response.status_code": 200
  },
  "retention_days": 90,
  "received": 1741792974
}
